#! /bin/bash
#
# anser, a simple processing system for use with linuxrip
# Copyright (C) 2006  madman2003 (madman2003@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

version=0.01

if [ $1 = '--help' ] &>/dev/null; then
	echo "anser ${version}"
	echo '--help: view this'
	exit
fi

# the bracket is used to make lack of input detectable
input="#${1}"
defaultinput="#${2}"

processinput() {
	# make input lowercase
	input=$(echo "${input}" | tr "A-Z" "a-z")
	defaultinput=$(echo "${defaultinput}" | tr "A-Z" "a-z")
	if [ ${input} == "#" ] &>/dev/null; then
		input="${defaultinput}"
	fi
}

processinput

responce='2'

while [ ${responce} == '2' ]; do
	if [[ (${input} == '#yes') || (${input} == '#y') || (${input} == '#1') ]]; then
		responce='1'
	elif [[ (${input} == '#no') || (${input} == '#n') || (${input} == '#0') ]]; then
		responce='0'
	else
		responce='2'
		echo 'Invalid responce, please anser with yes or no:' >&2
		read input
		# the input needs a bracket in front of it
		input="#${input}"
		processinput
	fi
done

echo "${responce}"