#!/bin/sh
#
# createnfo, a standalone nfo creator
# Copyright (C) 2006 madman2003 (madman2003@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA

version='0.02'

binpath='/usr/lib/linuxrip'

if [ $1 = '--help' ]
then
	echo "createnfo: version ${version}"
	echo '--create'
fi

information () {
	echo 'Please enter the information that is asked for, you will be given to do it again should you make a mistake'
	echo 'Artist:'
	read artist
	echo 'Album:'
	read album
	echo 'Year:'
	read year
	echo 'Genre:'
	read genre
	echo 'Ripper:'
	read ripper
	echo 'Did you encode flac? (0/1)'
	read encodeflac
	echo 'Did you encode musepack? (0/1)'
	read encodempc
	echo 'Did you encode wavpack? (0/1)'
	read encodewavpack
}

informationok () {
	echo 'Is this information correct? (yes/no)'
	echo "Artist: ${artist}"
	echo "Album: ${album}"
	echo "Year: ${year}"
	echo "Genre: ${genre}"
	echo "Ripper: ${ripper}"
	echo "Flac: ${encodeflac}"
	echo "Musepack: ${encodempc}"
	echo "Wavpack: ${encodewavpack}"
	read correct
	if [ ${correct} = 'no' ]
	then
		echo 'Information incorrect'
		information
	elif [ ${correct} = 'yes' ]
	then 
		echo 'Information correct'
	else
		echo 'Invalid choice'
		informationok
	fi
}

nfo () {
	nfofilename=($(echo "00_-_${artist}_-_${album}_-anon.nfo" | tr "' '" "_" | tr ":" "\0" | tr "A-Z" "a-z"))
	addnotes='no'
	echo 'Do you want to add notes to the nfo? (yes/NO)'
	read addnotes
	"${binpath}/nfowriter" '--createbasic' "${artist}" "${album}" "${year}" "${genre}" "${ripper}" "${encodeflac}" "{encodempc}" "{encodewavpack}" "${nfofilename}"
	if [ ${addnotes} = 'yes' ]
	then
		nfonotesok='0'
		while [ ${nfonotesok} = '0' ]
		do
			echo 'Please save file once you've written the notes, don't include notes: or anything like that'
			read dummy
			nano -w nfonotes.txt
			nfonotes=$(cat nfonotes.txt)
			rm "nfonotes.txt"
			echo "${nfonotes}"
			echo 'Are these ok? (yes/no)'
			read nfonotesok2
			if [ ${nfonotesok2} = 'yes' ]
			then
				nfonotesok='1'
			fi
		done
		"${binpath}/nfowriter" '--addnotes' "${nfonotes}" "${nfofilename}"
	elif [ ${addnotes} = 'no' ]
	then
		echo 'Notes will not be added'
	else
		echo 'Invalid choice'
		nfo
	fi
}

if [ $1 = '--create' ]
then
	information
	informationok
	nfo
fi