#! /bin/bash
#
# lowercdspeed, keep reducing cd speed for a certain amount of time
# Copyright (C) 2006  madman2003 (madman2003@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

version=0.01

if [ $1 = '--help' ] &>/dev/null; then
	echo "lowercdspeed ${version}"
	echo '--help: view this'
	exit
fi

# arg1 = device
# arg2 = maximumspeed
# arg3 = duration in 1/12 of a minute

speedcount=0
while (( ${speedcount} < $3 )); do
	cdspeed -d "$1" -s "$2"
	sleep 5
	let 'speedcount += 1'
done